# #Financial Modeling Prep API
#
# #FMP provides one of the most accurate data available on the market. Every endpoint is available in JSON format and most of them also in CSV format. Data is coming right from SEC filings after being serialized by us. Our API has over 50 endpoints and we are still growing by adding new endpoints every week. We also provide on demand custom endpoint available for our business clients.
#
# The version of the OpenAPI document: 3.0
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for Financialmodelingprep::FinancialStatementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "FinancialStatementsApi" do
  describe "test an instance of FinancialStatementsApi" do
    it "should create an instance of FinancialStatementsApi" do
      api_instance = Financialmodelingprep::FinancialStatementsApi.new
      # TODO expect(api_instance).to be_instance_of(Financialmodelingprep::FinancialStatementsApi)
    end
  end

  # unit tests for get_income_statements
  # Get Income Statements
  # Retreive income statements for stocks by symbol or CIK.
  # @param symbol
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :limit Number of results to return.
  # @option opts [String] :period Specify a quarterly income statement. Default is annual.
  # @option opts [String] :apikey API key for authn / authz
  # @option opts [String] :datatype Format of data to return
  # @return [IncomeStatementListResponse]
  describe "get_income_statements test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
