# #Financial Modeling Prep API
#
# #FMP provides one of the most accurate data available on the market. Every endpoint is available in JSON format and most of them also in CSV format. Data is coming right from SEC filings after being serialized by us. Our API has over 50 endpoints and we are still growing by adding new endpoints every week. We also provide on demand custom endpoint available for our business clients.
#
# The version of the OpenAPI document: 3.0
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for FinancialModelingPrep::IncomeStatementListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FinancialModelingPrep::IncomeStatementListResponse do
  describe "test an instance of IncomeStatementListResponse" do
    it "should create an instance of IncomeStatementListResponse" do
      # instance = FinancialModelingPrep::IncomeStatementListResponse.new
      # expect(instance).to be_instance_of(FinancialModelingPrep::IncomeStatementListResponse)
    end
  end
  describe "test attribute 'data'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
