# #Financial Modeling Prep API
#
##FMP provides one of the most accurate data available on the market. Every endpoint is available in JSON format and most of them also in CSV format. Data is coming right from SEC filings after being serialized by us. Our API has over 50 endpoints and we are still growing by adding new endpoints every week. We also provide on demand custom endpoint available for our business clients.
#
#The version of the OpenAPI document: 3.0
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 6.2.0
#

# Dependencies
require "crest"
require "log"

module 
  Log = ::Log.for("") # => Log for  source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Return the default `Configuration` object.
  def self.configure
    Configuration.default
  end

  # Customize default settings for the SDK using block.
  #
  # ```
  # .configure do |config|
  #   config.username = "xxx"
  #   config.password = "xxx"
  # end
  # ```
  def self.configure
    yield Configuration.default
  end
end

require ".//**"
